URL_SERVICE = "https://67974a8f-268d-43d2-9cc4-a1d52b42cdb2.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"